- src/assets/__tests__/Utils.spec.ts
- src/components/AutocompleteInput.vue
- src/components/HeaderMain.vue
- src/components/LimitOption.vue
- src/components/ResponseAction.vue
- src/components/__tests__/AutocompleteInput.spec.ts
- src/components/__tests__/EntriesRelationList.spec.ts
- src/components/__tests__/ResponseAction.spec.ts
- src/components/__tests__/SideMenu.spec.ts
- src/doc-editors/ContentFilterProfileEditor.vue
- src/doc-editors/RateLimitsEditor.vue
- src/doc-editors/SecurityPoliciesEditor.vue
- src/doc-editors/__tests__/SecurityPoliciesEditor.spec.ts
- src/router/index.ts
- src/views/CurieDBEditor.vue
- src/views/DocumentEditor.vue
- src/views/DocumentSearch.vue
- src/views/MainComponent.vue
- src/views/__tests__/CurieDBEditor.spec.ts
- src/views/__tests__/DocumentEditor.spec.ts
- src/views/__tests__/DocumentSearch.spec.ts
- src/views/__tests__/MasterComponent.spec.ts
- src/views/__tests__/Publish.spec.ts
- src/views/__tests__/VersionControl.spec.ts
Fix tests
Change MasterComponent to MainComponent
Change Router to work with imports of components
Add Prep work for DocumentList routing
Remove textarea input type from AutocompleteInput
> Support vue3 migration effort

- src/assets/styles/main.scss
- src/components/ResponseAction.vue
- src/components/SideMenu.vue
- src/components/responseActionConst.ts
- src/types/index.d.ts
- src/views/DocumentList.vue
- src/views/documentListConst.ts
Add displayFunction to document list column options
Add max height to all fields in document list
Add loading indciator for document list
Add functionality to download button for document list
Change column spacing in document list to be more spaced out in narrow columns
Change side menu item order to be aligned with our process-order
Move RESPONSE_ACTIONS const to its own file
> Document list additions

- src/assets/styles/main.scss
- src/components/GitHistory.vue
- src/views/DocumentList.vue
- src/views/documentListConst.ts
> Add git history to document list

- src/components/AutocompleteInput.vue
- src/components/EntriesRelationList.vue
- src/components/HeaderMain.vue
- src/components/LimitOption.vue
- src/components/SideMenu.vue
- src/components/TagAutocompleteInput.vue
- src/components/__tests__/AutocompleteInput.spec.ts
- src/components/__tests__/EntriesRelationList.spec.ts
- src/components/__tests__/HeaderMain.spec.ts
- src/components/__tests__/SideMenu.spec.ts
- src/vue-shims.d.ts
on the way to complete full coverage in the unit testing.
> Full coverage

- src/router/index.ts
- src/views/__tests__/DocumentList.spec.ts
> Fix tests for $route watch in DocumentList.spec.ts

- src/assets/styles/main.scss
- src/components/EntriesRelationList.vue
- src/components/RbzTable.vue
- src/components/__tests__/RbzTable.spec.ts
- src/types/index.d.ts
- src/views/DocumentList.vue
- src/views/__tests__/DocumentList.spec.ts
- src/views/documentListConst.ts
Add Rbz Table to Document List component
Add tests to cover documentListConst.ts
> Add Rbz Table component

- src/assets/RequestsUtils.ts
- src/components/SideMenu.vue
- src/components/__tests__/GitHistory.spec.ts
- src/components/__tests__/SideMenu.spec.ts
- src/components/__tests__/TagAutocompleteInput.spec.ts
- src/doc-editors/__tests__/ContentFilterProfileEditor.spec.ts
- src/doc-editors/__tests__/GlobalFilterListEditor.spec.ts
- src/doc-editors/__tests__/RateLimitsEditor.spec.ts
- src/doc-editors/__tests__/SecurityPoliciesEditor.spec.ts
- src/views/__tests__/CurieDBEditor.spec.ts
- src/views/__tests__/DocumentEditor.spec.ts
- src/views/__tests__/DocumentList.spec.ts
- src/views/__tests__/DocumentSearch.spec.ts
- src/views/__tests__/Publish.spec.ts
- src/views/__tests__/VersionControl.spec.ts
> Actually change conf server version to v3

- jest.config.js
- jest.setup.ts
- src/assets/RequestsUtils.ts
- src/assets/__tests__/RequestsUtils.spec.ts
- src/components/RbzTable.vue
- src/components/__tests__/RbzTable.spec.ts
- src/doc-editors/ContentFilterProfileEditor.vue
- src/doc-editors/ContentFilterRulesEditor.vue
- src/doc-editors/CustomResponseEditor.vue
- src/doc-editors/FlowControlPolicyEditor.vue
- src/doc-editors/RateLimitsEditor.vue
- src/doc-editors/__tests__/ContentFilterProfileEditor.spec.ts
- src/doc-editors/__tests__/ContentFilterRulesEditor.spec.ts
- src/doc-editors/__tests__/CustomResponseEditor.spec.ts
- src/doc-editors/__tests__/FlowControlPolicyEditor.spec.ts
- src/views/DocumentList.vue
- src/views/__tests__/DocumentList.spec.ts
- vue.config.js
Add more confiugration to RbzTable
Fix issues in some tag auto complete inputs
Fix rate limit number inputs not marked as numbers
> Add option to send request to Reblaze Backend

- src/assets/DatasetsUtils.ts
- src/assets/__tests__/DatasetsUtils.spec.ts
- src/assets/styles/main.scss
- src/components/LimitOption.vue
- src/components/RbzTable.vue
- src/components/SideMenu.vue
- src/components/__tests__/RbzTable.spec.ts
- src/components/__tests__/SideMenu.spec.ts
- src/doc-editors/SecurityPoliciesEditor.vue
- src/doc-editors/__tests__/RateLimitsEditor.spec.ts
- src/views/DocumentEditor.vue
- src/views/DocumentList.vue
- src/views/__tests__/DocumentEditor.spec.ts
- src/views/__tests__/DocumentList.spec.ts
- src/views/documentListConst.ts
Change RbzTable buttons to be inside dropdown
Change SideMenu items order
Fix Security Policy Map Entry ID display
Add redirectToList button to Document Editor
Add Security Policies list
Add Security Policies to Side Menu
> General improvements to the system

- .github/workflows/deploy-to-gcs.yaml
create workflow to buiid the ui and push to GCS bucket
> Create workflow deploy-to-gcs

- src/assets/DatasetsUtils.ts
- src/components/AutocompleteInput.vue
- src/doc-editors/ACLEditor.vue
- src/doc-editors/ContentFilterProfileEditor.vue
- src/doc-editors/GlobalFilterListEditor.vue
- src/doc-editors/ProxyTemplateEditor.vue
- src/doc-editors/RateLimitsEditor.vue
- src/doc-editors/RoutingProfileEditor.vue
- src/doc-editors/SecurityPoliciesEditor.vue
- src/doc-editors/__tests__/ACLEditor.spec.ts
- src/doc-editors/__tests__/ContentFilterProfileEditor.spec.ts
- src/doc-editors/__tests__/GlobalFilterListEditor.spec.ts
- src/doc-editors/__tests__/RateLimitsEditor.spec.ts
- src/types/index.d.ts
- src/views/MainComponent.vue
- src/views/RoutingProfileList.vue
Change Routing Profile according to demo comments. Added path mapping, backend is now dropdown, cloud functions is selector and attached to path
Change Proxy Template according to demo comments. Removed unused fields Change Action input to be dropdown
Add Tags input to Rate Limit
Fix setImmediate not working properly
Fix text issues in Security Policy page (title of path mapping Match input)
Fix text issue in Global Filter page (`entries Relation` instead of `Sections Relation`)
> Changes according to demo comments and QA initial tests

- src/doc-editors/WebProxyEditor.vue
> Fix server names

- src/assets/DatasetsUtils.ts
- src/assets/__tests__/DatasetsUtils.spec.ts
- src/assets/backendServicesConsts.ts
- src/components/RbzTable.vue
- src/components/SideMenu.vue
- src/doc-editors/BackendServiceEditor.vue
- src/doc-editors/CustomResponseEditor.vue
- src/doc-editors/FlowControlPolicyEditor.vue
- src/doc-editors/SecurityPoliciesEditor.vue
- src/doc-editors/WebProxyEditor.vue
- src/doc-editors/__tests__/ACLEditor.spec.ts
- src/doc-editors/__tests__/ContentFilterProfileEditor.spec.ts
- src/doc-editors/__tests__/FlowControlPolicyEditor.spec.ts
- src/doc-editors/__tests__/RateLimitsEditor.spec.ts
- src/doc-editors/__tests__/SecurityPoliciesEditor.spec.ts
- src/router/index.ts
- src/types/index.d.ts
- src/views/BackendServiceList.vue
- src/views/ProxyTemplateList.vue
- src/views/WebProxyList.vue
- src/views/__tests__/DocumentEditor.spec.ts
- src/views/__tests__/DocumentList.spec.ts
- src/views/__tests__/DocumentSearch.spec.ts
- src/views/documentListConst.ts
Add Backend Services list page
Add Backend Services edit page
Change default Custom Response for new items to be `monitor` as `default` does not exist
Remove `Security Policy Id` and `Path Matching Id` from `Count by` field of Flow Control
Remove `Action` column from Flow Control list page
Fix table spacing issue in Secuirty Policy when Rate Limits had long description
> Add Backend Services pages

- src/components/RbzTable.vue
- src/components/__tests__/RbzTable.spec.ts
- src/doc-editors/SecurityPoliciesEditor.vue
- src/views/BackendServiceList.vue
- src/views/MobileSDKList.vue
- src/views/ProxyTemplateList.vue
- src/views/RoutingProfileList.vue
- src/views/WebProxyList.vue
Fix bug in RbzTable button row not showing for most tables
Fix bug in SecurityPoliciesEditor showing Content Filter Profile selector twice
> Fix for bugs in RbzTable and SecurityPoliciesEditor

- src/components/SideMenu.vue
- src/doc-editors/BackendServiceEditor.vue
- src/doc-editors/CustomResponseEditor.vue
- src/doc-editors/DynamicRulesEditor.vue
- src/doc-editors/FlowControlPolicyEditor.vue
- src/doc-editors/MobileSDKEditor.vue
- src/doc-editors/ProxyTemplateEditor.vue
- src/doc-editors/RoutingProfileEditor.vue
- src/doc-editors/WebProxyEditor.vue
- src/views/BackendServiceList.vue
- src/views/DocumentEditor.vue
- src/views/DocumentList.vue
- src/views/DocumentSearch.vue
- src/views/MobileSDKList.vue
- src/views/ProxyTemplateList.vue
- src/views/Publish.vue
- src/views/RoutingProfileList.vue
- src/views/VersionControl.vue
- src/views/WebProxyList.vue
- src/views/__tests__/DocumentList.spec.ts
- src/views/documentListConst.ts
- Add mask to `configs/` api calls to drastically increase performance throughout the system
- Fix bug in sequence items in Flow Control editor. Trashcan icon shows under Plus icon instead of next to it
- Change title of `Limits` column to `Thresholds` and change new line to comma in Rate Limits list
- Add tags column to Flow Controls list
- Add tags column to Rate Limits list
- Add tags column to ACL Profiles list
- Add tags column to Content Filter Profiles list
- Change title of `Headers` field in CustomResponseEditor.vue to be `Response Headers` for `Custom` type and `Request Headers` for `Monitor` type
- Fix bug where `Headers` are not saved correctly for `Monitor` type in CustomResponseEditor.vue
- Change order of input fields in DynamicRulesEditor.vue. New order: Target, Threshold, …
> Various UI changes

- src/components/SideMenu.vue
- src/components/__tests__/SideMenu.spec.ts
- src/doc-editors/ContentFilterProfileEditor.vue
- src/router/index.ts
- src/views/HelpAndSupport.vue
> HelpAndSupport page

- src/types/index.d.ts
> Type optional properties hotfix

- src/views/Publish.vue
- src/views/VersionControl.vue
Fix publish page not displaying
Fix version control page not displaying data correctly
> Remove x-fields from places where it's not needed

- src/assets/DatasetsUtils.ts
- src/assets/RequestsUtils.ts
- src/doc-editors/CloudFunctionsEditor.vue
- src/doc-editors/__tests__/CloudFunctionsEditor.spec.ts
- src/types/index.d.ts
- src/views/__tests__/DocumentEditor.spec.ts
> changes to cloud functions

- src/assets/DatasetsUtils.ts
- src/components/LimitOption.vue
> new attributes for default

- src/components/LabeledTags.vue
- src/doc-editors/ACLEditor.vue
- src/doc-editors/ContentFilterProfileEditor.vue
- src/doc-editors/ContentFilterRulesEditor.vue
- src/doc-editors/FlowControlPolicyEditor.vue
- src/doc-editors/RateLimitsEditor.vue
Add automatic tags to ACL Profile editor
Add automatic tags to Content Filter Profile editor Add automatic tags to Flow Control editor
Add automatic tags to Rate Limit editor
Change automatic tags in Content Filter Rules editor to use the new component
> Add Labeled Tags component

- src/components/RbzTable.vue
- src/reblaze-dashboards/DefaultDashboard.vue
- src/views/Dashboard.vue
Fix datalayer connection
Add "No results found" message in Dashboard when no results found
> Dashboard fixes & Datalayer connection

- src/assets/RequestsUtils.ts
- src/components/QuarantinedList.vue
- src/components/SideMenu.vue
- src/stores/BranchesStore.ts
- src/views/BackendServicesList.vue
- src/views/ConfigTemplatesList.vue
- src/views/Dashboards.vue
- src/views/DocumentEditor.vue
- src/views/DocumentList.vue
- src/views/DynamicRulesList.vue
- src/views/MobileSDKsList.vue
- src/views/Publish.vue
- src/views/RoutingProfilesList.vue
- src/views/ServerGroupsList.vue
Fix commit counters on branch commit not updating
Fix publish info not updating on page load if branches already loaded
Fix default sort column in all list views to be Name
> Demo fixes

- src/reblaze-dashboards/DefaultDashboard.vue
> Add escape for metrics data

- src/doc-editors/CustomResponsesEditor.vue
Replace between Headers and status, and make Headers bigger than it was
> Custom response editor changes

- src/assets/DatasetsUtils.ts
- src/components/LimitOption.vue
- src/doc-editors/SecurityPoliciesEditor.vue
- src/types/index.d.ts
> Add `session` and `session_ids` to Security Policy

- src/doc-editors/RoutingProfilesEditor.vue
- src/doc-editors/SecurityPoliciesEditor.vue
- src/doc-editors/ServerGroupsEditor.vue
- src/doc-editors/__tests__/SecurityPoliciesEditor.spec.ts
- src/reblaze-dashboards/DefaultDashboard.vue
- src/views/Dashboards.vue
Change metabase iframe to take 100% of the page height
Fix link from Security Policy to new Rate Limit Rule
Fix link from Routing Profiles to new Edge Function
Add missing label to Server Groups delete button
> Fix some stuff before the demo

- src/assets/DatasetsUtils.ts
- src/components/SideMenu.vue
- src/doc-editors/ProxyTemplatesEditor.vue
- src/doc-editors/ServerGroupsEditor.vue
- src/router/index.ts
- src/types/index.d.ts
- src/views/ProxyTemplatesList.vue
- src/views/ServerGroupsList.vue
> changing config-templates to proxy-templates

- src/doc-editors/BackendServicesEditor.vue
> Change input type to number

- src/components/QuarantinedList.vue
- src/components/RbzTable.vue
- src/doc-editors/BackendServicesEditor.vue
- src/views/MainComponent.vue
- vue.config.js
> changing table classes for QuarantinedList

- src/doc-editors/RoutingProfilesEditor.vue
- src/doc-editors/SecurityPoliciesEditor.vue
> fix bug duplicate and add new profile

- src/doc-editors/RoutingProfilesEditor.vue
- src/doc-editors/SecurityPoliciesEditor.vue
- src/doc-editors/ServerGroupsEditor.vue
> fix bug 363

- src/components/RbzTable.vue
- src/doc-editors/ProxyTemplatesEditor.vue
- src/doc-editors/ServerGroupsEditor.vue
> adding modal for trusted sources add edit delete

- .github/workflows/build-image.yaml
> Fix docker build tag

- src/components/LimitOption.vue
- src/components/SecurityPoliciesConnections.vue
- src/doc-editors/RateLimitRulesEditor.vue
- src/views/DocumentEditor.vue
> bobble policy connections Bug #215

- .gitignore
- src/components/EventsLogRow.vue
- src/components/RbzChart.vue
- src/components/RbzDatePicker.vue
- src/components/RbzDatePickerCustomTimePicker.vue
- src/reblaze-dashboards/DefaultDashboard.vue
- src/views/Dashboards.vue
- src/views/EventsLog.vue
Remove some unneeded API calls from Document Editor
Fix date picker to work with UTC time in the presets
Change date picker's time picker component to be more user friendly
Change Dashboard and Events Log to use the same datepicker component
Add "Ungroup" button in Events Log to quickly ungroup events
Remove empty filters from Events Log filter before sending the query
Fix issue with Events Log filter not filtering nested values correctly (args, cookies, headers, proxy)
Fix bug where Pie Chart percentage was not divided by 100 in the correct location
Fix issue with legend in RbzChart going off screen when too far to the right
> Bug fixes in Events Log / Dashboard

- src/components/QuarantinedList.vue
> time zone added to timestamp of quarantined

- src/components/SecurityPoliciesConnections.vue
> fix remove connection emit

- src/views/DocumentList.vue
- src/views/DynamicRulesList.vue
Add Action column for Dynamic rules, Rate limits and Flow control as well
> Add Action column

- src/assets/DateTimeUtils.ts
- src/assets/__tests__/DateTimeUtils.spec.ts
- src/components/EventsLogCharts.vue
- src/components/QuarantinedList.vue
- src/components/RbzChart.vue
- src/components/RbzTable.vue
- src/reblaze-dashboards/DefaultDashboard.vue
- src/views/DynamicRulesList.vue
Change select all behavior in tables to select current page only
Change display values for future times to `X time from now` instead of full dates when applicable
Fix issue in Quarantined where times were not presented in UTC on hover
> Quarantined page changes

- src/assets/RequestsUtils.ts
- src/assets/__tests__/RequestsUtils.spec.ts
- src/components/DnsPage.vue
- src/components/RbzTable.vue
- src/doc-editors/RateLimitRulesEditor.vue
- src/types/index.d.ts
- src/views/DocumentEditor.vue
- src/views/EventsLog.vue
- src/views/ProxyTemplatesList.vue
- src/views/SslList.vue
Fix tooltip display text in Proxy Templates list page for `Static IP Rate Limit` and `Proxy Timeout` columns
Fix row sizing for DNS table
Fix issue in SSL where `soon to expire` / `expired` certificates weren't color coded correctly
> Fix various bugs

- src/assets/styles/main.scss
- src/reblaze-dashboards/DefaultDashboard.vue
> Fix performance issue in dashboard loading thousands of rows in each top-table

- src/doc-editors/ProxyTemplatesEditor.vue
> Fix for trusted sources build

- src/assets/RequestsUtils.ts
> Fix redirect on server response missing encoding

- src/assets/Utils.ts
- src/components/SideMenu.vue
- src/router/index.ts
- src/stores/userStore.ts
Add auth guard to router depending on current user access level. User should be redirected to `/prod/premiun` when trying to access these pages without a sufficient access level
Change side menu items to be disabled when current user access level is not sufficient to access the coresponding pages
> Auth guard
